version = 0.1

[default.build.parameters]
beta_features = true
[default.sync.parameters]
beta_features = true

[default.deploy.parameters]
stack_name = "webrs"
resolve_s3 = true
s3_prefix = "webrs"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
