default:
  prompts:
    summarisation: |
      Summarise the blog post in one sentence.
      This one sentence should be a concise preview of what the blog post is about without revealing the conclusion.
      Use a similar tone of voice as the blog post itself. Do not summarise in third person.
      Do not start the summary with "The blog post". Seriously though, don't start with "the blog".
      Also don't start with "this post".
