AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Rust binary
Resources:
  RustFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties: function_a
    Properties:
      CodeUri: ./target/lambda/webrs/
      Handler: bootstrap
      Runtime: provided.al2023
      Tracing: Active
      Environment:
        Variables:
          DATABASE_URL:
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
Outputs:
  RustFunction:
    Description: Lambda Function ARN
    Value: !GetAtt RustFunction.Arn
