AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Rust binary
Resources:
  WebRsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties: function_a
    Properties:
      FunctionName: WebRsFunction
      CodeUri: ./target/lambda/webrs/
      Handler: bootstrap
      Runtime: provided.al2023
      FunctionUrlConfig:
        AuthType: NONE
      Tracing: Active
      Environment:
        Variables:
          DATABASE_URL:
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
  WebRsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/WebRsLogs
Outputs:
  WebRsFunction:
    Description: Lambda Function ARN
    Value: !GetAtt WebRsFunction.Arn
