AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Rust binary
Resources:
  WebRsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties: function_a
    Properties:
      FunctionName: WebRsFunction
      CodeUri: ./target/lambda/webrs/
      Handler: bootstrap
      Runtime: provided.al2023
      FunctionUrlConfig:
        AuthType: NONE
      Tracing: Active
      Environment:
        Variables:
          DATABASE_URL: postgresql://daniel:7zw0C9QkVn7hnQlJ2_2ALQ@dry-reptile-8706.7tc.aws-eu-central-1.cockroachlabs.cloud:26257/webrs?sslmode=verify-full
      Events:
        RootApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        AnyApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
  WebRsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/WebRsLogs
  WebRsCustomDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: danielsteman.com
      RegionalCertificateArn: arn:aws:acm:eu-central-1:730335219622:certificate/f54b77ad-9ded-4c03-9f73-bea389d86eca
      EndpointConfiguration:
        Types:
          - REGIONAL

Outputs:
  WebRsFunction:
    Description: Lambda Function ARN
    Value: !GetAtt WebRsFunction.Arn
