name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.18"
      - name: Install dependencies
        run: |
          yarn install
          yarn prod
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides DatabaseUrl="${{ secrets.DATABASE_URL }}"
