name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.18"

      - name: Install dependencies
        run: |
          yarn install
          yarn prod
